### ISSUE TITLE
Seems to break with Babel v7

### ISSUE THREAD

**Issue by raido** [jacobmischka/babel-plugin-object-values-to-object-keys#1]
```
import { something } from "x";

Object.values(something)
```

is transformed as:

```
Object.keys(_x.something).map(key => something[key])
```

Which ends as ReferenceError, because `something` is not defined anywhere.

**Comment by jacobmischka** [comment]
Thanks for the report, I'll try to take a look at this today.

**Comment by jacobmischka** [comment]
Hm, can you please post your babel config? I think this is caused by a bad ordering, this plugin should likely be toward the end of your `plugins` list.

**Comment by raido** [comment]
```
babel: {
      plugins: [
        'babel-plugin-object-values-to-object-keys'
      ]
    },
```

BUT this is in Ember.js app context, taken from `ember-cli-build.js` - so there might be other factors that are not clearly visible why this would fail.

**Comment by raido** [comment]
I have not been able to reproduce this with a test case. To give more context the final code ends up as a module with `define('something', function(x, t) { ... })` and inside that module code the final output is broken.

Closing for now.

**Comment by jacobmischka** [comment]
Sorry I couldn't have been of more help! Please reopen if you find that it is in fact the fault of this plugin.
